services:
  postgres:
    image: postgres:16-alpine
    container_name: kachok_db
    environment:
      POSTGRES_USER: kachok_user
      POSTGRES_PASSWORD: kachok_pass
      POSTGRES_DB: kachok_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U kachok_user" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
