from .auth import router as auth_router
from .public import router as public_router
from .profile import router as profile_router
from .leaders import router as leaders_router
from .results import router as results_router
from .stats import router as stats_router
from .records import router as records_router
from .admin import router as admin_router
from .achievements import router as achievements_router