"""add category slug and user profile fields

Revision ID: ae492f1636c9
Revises: fc8d7fbde95a
Create Date: 2026-06-29 14:48:52.521951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae492f1636c9'
down_revision: Union[str, Sequence[str], None] = 'fc8d7fbde95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('category', sa.Column('slug', sa.String(length=30), nullable=True))
    op.create_unique_constraint(None, 'category', ['slug'])
    op.add_column('users', sa.Column('gym_name', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('users', sa.Column('weight_class', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'weight_class')
    op.drop_column('users', 'city')
    op.drop_column('users', 'gym_name')
    op.drop_constraint(None, 'category', type_='unique')
    op.drop_column('category', 'slug')
    # ### end Alembic commands ###
